title: lucasvazq.py
email: lucas5zvazquez@gmail.com
description: Python programmer and Web Developer
baseurl: "/"
url: "http://lucasvazq.github.io/"
github_username: lucasvazq

theme: minima
plugins:
  - jekyll-feed
include: ['_next', '_buildManifest.js', '_ssgManifest.js', '_error-ddb4b255e666acc8c749.js', '_app-d4e9be6cc605795f6cac.js', '.well-known']
